{% set name = "python-pgplot" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_pgplot-{{ version }}.tar.gz
  sha256: 3af95c1aafd78994c6b46b4c478584c033eef32affb82c3c1d4e7fe07f6df48d

build:
  number: 0
  skip: true  # [win]  # Windows not supported

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - pkg-config
    - make
    - wget  # [unix]
    - tar   # [unix]
    - gzip  # [unix]
    - xorg-libx11
  host:
    - python
    - pip
    - setuptools >=45
    - wheel
    - numpy >=2.0.0rc1
    - pkgconfig
    - cairo
    - xorg-libx11
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cairo
    - xorg-libx11

test:
  imports:
    - ppgplot
    - ppgplot._ppgplot
  commands:
    - python -c "import ppgplot; print('python-pgplot imported successfully')"

about:
  home: https://github.com/haavee/ppgplot
  license: GPL-3.0-or-later
  license_family: GPL
  summary: Python bindings for PGPLOT
  description: |
    Python bindings for PGPLOT graphics library. PGPLOT is a Fortran- or 
    C-callable, device-independent graphics package for making simple scientific 
    graphs. This package provides Python bindings through the giza library.
  doc_url: https://github.com/haavee/ppgplot
  dev_url: https://github.com/haavee/ppgplot

extra:
  recipe-maintainers:
    - haavee
